[project]
name = "adicts"
version = "0"
description = "(a)rithmetic operations for (dict)ionaries"
authors = [{ name = "William Norland"}]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "numpy",
]

[project.urls]
Homepage = "https://github.com/willayy/adict"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]